export const sharedTools = [
  {
    id: "cowart",
    name: "Cowart AI 创作画布",
    packageName: "cowart",
    type: "tool-plugin",
    typeLabel: "工具插件 · 含 3 个 Skill",
    status: "已收集",
    category: "AI 视觉创作",
    summary: "在一张画布里生成图片、批注修改，并把新版本放在原图旁边。",
    description: "Cowart 是一套面向 AI 图片创作与改图的画布工具。它把生成、批注修改和版本对照放在同一张画布中，适合一边讨论、一边迭代视觉方案。",
    tags: ["图片生成", "批注改图", "版本对照"],
    useCases: [
      "快速探索海报、插画、视觉素材等图片方向",
      "直接在截图上写修改意见，再生成干净的新版本",
      "保留原图、批注和修改稿，方便团队前后对照",
    ],
    capabilities: [
      "cowart-image-gen：生成图片并放入指定画布位置",
      "cowart-image-edit：理解批注截图，生成修改稿并排展示",
      "cowart-open-canvas：打开、重新打开或刷新 Cowart 画布",
    ],
    workflow: [
      "打开 Cowart 画布，选中图片占位区域或直接描述想生成的内容",
      "生成图片后，在需要调整的位置添加批注并提供批注截图",
      "修改稿自动放在原图旁边，保留原图与批注用于复盘",
    ],
    deliverables: ["生成或修改后的图片", "保留前后版本的创作画布", "随项目保存的画布与图片资产"],
    limitations: [
      "Cowart 是一个工具插件，不是单一 Skill；当前包含 3 个配套 Skill",
      "批注改图需要提供对应的批注截图，工具不会扫描整张画布猜测修改意图",
      "主要面向位图创作，不替代矢量设计、交互原型或完整设计工程",
    ],
  },
  {
    id: "ui-wireframe-workflow",
    name: "移动端低保真原型工作流",
    packageName: "ui-wireframe-workflow",
    type: "skill",
    typeLabel: "Skill",
    status: "已收集",
    category: "产品设计",
    summary: "把产品想法整理成设计规范和可预览的移动端线框图。",
    description: "从一个产品需求出发，通过对话梳理目标用户、核心功能和主要页面，先建立统一的设计系统文档，再生成可直接在浏览器中预览的移动端低保真原型。",
    tags: ["需求梳理", "信息架构", "低保真原型"],
    useCases: [
      "需求早期讨论和产品方向澄清",
      "产品、设计与研发一起确认页面结构",
      "进入高保真设计前验证信息架构和核心流程",
    ],
    capabilities: [
      "通过对话收集目标用户、核心功能和关键页面",
      "使用已有设计规范，或采用内置的移动端默认规范",
      "生成 375×812、简体中文、支持滚动与固定导航的多页面线框图",
    ],
    workflow: [
      "确认目标用户、核心功能，以及是否已有设计规范",
      "根据已有规范或内置默认规范生成设计系统文档",
      "再生成单文件线框原型，根据反馈修改直至确认",
    ],
    deliverables: ["docs/design-system.md 设计系统文档", "wireframes.html 单文件移动端线框原型"],
    limitations: [
      "只做到低保真线框确认，默认使用灰阶表达",
      "不负责品牌配色、高保真视觉、React 工程或真实后端",
      "会先询问是否已有设计规范，最终原型需要用户确认后才算完成",
    ],
  },
];
